# Generated by Django 4.1.3 on 2023-01-10 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text_preview', models.TextField(blank=True, null=True, verbose_name='Текст превю')),
                ('text', models.TextField(verbose_name='Текст')),
                ('publish_date', models.DateTimeField(verbose_name='Дата публікації')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='дата оновлення публікації')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='дата створення публікації')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategorymodel')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Стаття',
            },
        ),
    ]
