# Generated by Django 4.1.3 on 2023-01-10 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogCategoryModel',
            new_name='BlogCategory',
        ),
    ]
